### ISSUE TITLE
Бросание кубика

### ISSUE THREAD

**Issue by RitoAgent** [RitoAgent/Pyxel-Python#1]
![Image](https://github.com/RitoAgent/Pyxel-Python/assets/132717651/6a66d4d7-c9b1-46cf-bf0c-b2990168b61b)

У нас есть 20-гранный кубик (20 треугольных сторон). Нужно создать модель броска кубика в pyxel с условием завершения цикла броска. 
Что для этого нужно сделать я опишу ниже:
1) В python создать метод picture который размещает картинку на экране по координатам которые можете задать сами.
2) Саму картинку кубика отрисуете в редакторе pyxel/kitao, который вы скачали вместе с интерпретатором питона 
(напоминаю что работаем в виртуальной среде, а не в системном питоне)
3) Звуковые эффекты добавляете методом music и также как и с картинкой музыку и звуковые эффекты 
4) выполнение условия завершения цикла после броска(проверка на выполнение условия приложу в картинке)
P.S: пример броска кубика на сайте https://www.roll-dice-ru.com/1-%D0%BA%D1%83%D0%B1%D0%B8%D0%BA/20-%D0%B3%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9.html
Примерно тоже самое сделать в Pyxel и в звуковом сопровождении.

![Image](https://github.com/RitoAgent/Pyxel-Python/assets/132717651/2130fba9-d1db-4dee-97b0-4c3f9ed2c7eb)

**Comment by RitoAgent** [comment]
I. Ну это будем более простой вариант бросок кубика. Поскольку это 2D пиксельная графика 8 бит. Я думаю просто будет кубик в статичном положении и в центре на треугольнике будет меняться цифры при броске пока не выпадет число от 1 до 20. Сам кубик можно просто в виде png определенных размеров в графическом редакторе нарисовать
II. Для начала нужно сделать эффект броска + катания костей. А далее в зависимости от того какие числа выпадают делать соотвествующий звуковой эффект. 
III. Чтобы осуществить бросок нужно просто нажать на изображения кубика с мышки. А вот насчет интерфейса нужно еще подумать. Да и сам бросок кубика еще только начало на самом деле. Потому что это нужно для фактически настольной игры в пикселе.

**Comment by KonstantinKlepikov** [comment]
@RitoAgent итак, давай составим ТЗ здачи:

Игра в бросание 20-тигранного кубика.

1. на главном экране размещается изображение 2-тигранника
2. изображение статическое - кубик не анимируется
3. при "бросании" кубика изменяется цифра на его лицевой стороне
4. "бросок" осуществляется кликом мышки (или нажатием клавиши)
5. момент броска кубика, результат броска, "катание", сопровождается звуковыми эффектами
6. условие победы: выпало значение больше загаданного
7. необходимо реализовать ввод "загаданного" значения перед броском. Это требует поля для ввода и тестового запроса к пользователю - это стартовый экран
8. Необходим экран конца игры, когда бросок кубика соответствует условию.

Исход из этого я поставлю пул задач. ТЗ зафиксирвоано в [ВИКИ репозитори](https://github.com/RitoAgent/Pyxel-Python/wiki/%D0%98%D0%B3%D1%80%D0%B0-%D0%B2-%D0%B1%D1%80%D0%BE%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-20%E2%80%90%D1%82%D0%B8%D0%B3%D1%80%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D1%83%D0%B1%D0%B8%D0%BA%D0%B0.-%D0%A2%D0%97)
